### ISSUE TITLE
Android wallet was no connection

### ISSUE THREAD

**Issue by kumruhakan** [BLCdeveloper/cryptobullcoin#12]
Hi guys my android wallet is always no connected anybody help me please?

**Comment by duyphuongls** [comment]
cách đây 1 tuần ví bullcoin androi còn có bullcoin bây giờ đã biến mất không tìm được BQuAgonVmCF1DgCbBW1HACqx6NbEJZCvrt

**Comment by BLCdeveloper** [comment]
We are working hard to hopefully have the doors open and ready for business sometime in September. Many people have asked "what's taking so long?" Lol, we feel the same way! We wanted to have a good cryptocurrency and provide our customers a safe and enjoyable payment experience.

Please notes we will updates at https://bullcoin.io/
Thanks a lots!

**Comment by nolanle** [comment]
https://drive.google.com/file/d/0B-g1uBauhyRIc0hONnVKYmhEVUU/view?usp=sharing

We had update new version of wallet: https://drive.google.com/file/d/0B-g1uBauhyRIc0hONnVKYmhEVUU/view?usp=sharing

Thanks!
