### ISSUE TITLE
Bullcoin website and explorer not accesible.

### ISSUE THREAD

**Issue by hotlocco** [BLCdeveloper/cryptobullcoin#18]

**Comment by hotlocco** [comment]
Is it safe to send BLC from my wallet?

**Comment by BLCdeveloper** [comment]
send to where, man?

**Comment by hotlocco** [comment]
Blc explorer website is not accessible, is it safe to send blc to pc wallet from ccex?

**Comment by BLCdeveloper** [comment]
no problem bro
