### ISSUE TITLE
android wallet not connected

### ISSUE THREAD

**Issue by norzaini5561** [BLCdeveloper/cryptobullcoin#3]
guys what happen to android wallet was shown no connection and still not receive blc ..check at explorer shown was distribute on 4/8...thanks.

**Comment by ainafaisal** [comment]
Android wallet not connected plz help

**Comment by arsel51** [comment]
Android wallet not connected but in explorer hv transaction.pls help 
Your support is highly needed

**Comment by VYACHESLAV111** [comment]
Otprav'te moyu podderzhku: cryptobullcoin koshelek androi ne mozhet podklyuchit'sya, pishet net svyazi ,chtoby poluchit' bullcoin. YA proveril adres: BTcAR3LLxkgmaEZrmu9YC6WTLATbzetDH8 poluchit' den'gi ot ethtrade.

**Comment by BLCdeveloper** [comment]
#12 
We will update soon, please check at

**Comment by VYACHESLAV111** [comment]
everything also remained unchanged

**Comment by VYACHESLAV111** [comment]
can once again download the program and install on android, give a link from where you can download the updated program
