### ISSUE TITLE
Lose my prasha recovery

### ISSUE THREAD

**Issue by johorbrutal76** [BLCdeveloper/cryptobullcoin#5]
Princess Laila:
Dear sir/madam

How to recover ur passphrase.I forgot to copy.

I only have my passwrd and the address which the amount was tranfered to

My wallet address:
BEbcGGWJZWcQvBDYKamQ2DxUyGGBKwexWg

Just so u knw i was using my brothers phone when creating the ewallet with cryptobullion.
Now that i have my phone back i forgot my passphrase.My brothers fon no longer has my ewallet..

Please assist to resolve this matter

Thanking you un advance for you kind cooperation

**Comment by yerten3117** [comment]
Hello, if you have not saved the words before, you can not save your wallet

Sorry for not helping

**Comment by yerten3117** [comment]
name grain toe tower outdoor happy spatial stove this claim fade pledge wild library stomach name scissors ritual
Words like this
